### ISSUE TITLE
添加反向代理后，域名访问无法正常使用

### ISSUE THREAD

**Issue by Mr-Liu1996** [zhaojun1998/zfile#159]
## 我的环境
Ubuntu 18.04.5

## 错误日志
主页：
![msedge_sciWhByigu.png](http://tu.ifanque.top/2020/10/08/7b5161917e6fb.png)
后台：
![msedge_EEF6AwIFoH.png](http://tu.ifanque.top/2020/10/08/db890a154b94b.png)

## 期望行为
正常使用

## 当前行为
尚未初始化驱动器, 请联系管理员.

## 描述 bug 细节，确认出现此问题的复现步骤，例如点击了哪里，发生了什么情况？
访问域名提示：
尚未初始化驱动器, 请联系管理员.

点击首页提示：
Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: "undefined"

Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: "undefined"

**Comment by Mr-Liu1996** [comment]
> ## 我的环境
> Ubuntu 18.04.5
> 
> ## 错误日志
> 主页：
> ![](https://cdn.jsdelivr.net/gh/Mr-Liu1996/uploadimg/imgmsedge_sciWhByigu.png)
> 后台：
>![](https://cdn.jsdelivr.net/gh/Mr-Liu1996/uploadimg/imgmsedge_EEF6AwIFoH.png)
> 
> ## 期望行为
> 正常使用
> 
> ## 当前行为
> 尚未初始化驱动器, 请联系管理员.
> 
> ## 描述 bug 细节，确认出现此问题的复现步骤，例如点击了哪里，发生了什么情况？
> 访问域名提示：
> 尚未初始化驱动器, 请联系管理员.
> 
> 点击首页提示：
> Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: "undefined"
> 
> Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: "undefined"

**Comment by heiybb** [comment]
你登录的link似乎不对
尝试使用 https://pan.ifanque.top/#/admin
添加驱动器之后首页可得以显示正常

**Comment by zhaojun1998** [comment]
是的，你地址输错了，应该是 http:/ip:port/#/admin
